// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"context"

	bm "go-online/lib/net/http/blademaster"
	"go-online/lib/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathIdentifyGetCookieInfo = "/passport.service.identify.api.Identify/GetCookieInfo"
var PathIdentifyGetTokenInfo = "/passport.service.identify.api.Identify/GetTokenInfo"

// IdentifyBMServer is the server API for Identify service.
type IdentifyBMServer interface {
	// CookieInfo identify info by cookie.
	GetCookieInfo(ctx context.Context, req *GetCookieInfoReq) (resp *GetCookieInfoReply, err error)

	// TokenInfo identify info by token.
	GetTokenInfo(ctx context.Context, req *GetTokenInfoReq) (resp *GetTokenInfoReply, err error)
}

var IdentifySvc IdentifyBMServer

func identifyGetCookieInfo(c *bm.Context) {
	p := new(GetCookieInfoReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := IdentifySvc.GetCookieInfo(c, p)
	c.JSON(resp, err)
}

func identifyGetTokenInfo(c *bm.Context) {
	p := new(GetTokenInfoReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := IdentifySvc.GetTokenInfo(c, p)
	c.JSON(resp, err)
}

// RegisterIdentifyBMServer Register the blademaster route
func RegisterIdentifyBMServer(e *bm.Engine, server IdentifyBMServer) {
	IdentifySvc = server
	e.GET("/passport.service.identify.api.Identify/GetCookieInfo", identifyGetCookieInfo)
	e.GET("/passport.service.identify.api.Identify/GetTokenInfo", identifyGetTokenInfo)
}
